"""Initial migration

Revision ID: 7c2b49752456
Revises: 
Create Date: 2019-03-26 14:27:06.122496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2b49752456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=128), nullable=True),
    sa.Column('movie_title', sa.Unicode(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_create_datetime'), 'movie', ['create_datetime'], unique=False)
    op.create_index(op.f('ix_movie_imdb_id'), 'movie', ['imdb_id'], unique=True)
    op.create_index(op.f('ix_movie_movie_title'), 'movie', ['movie_title'], unique=True)
    op.create_index(op.f('ix_movie_points'), 'movie', ['points'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('join_datetime', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_join_datetime'), 'user', ['join_datetime'], unique=False)
    op.create_index(op.f('ix_user_points'), 'user', ['points'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_create_datetime'), 'question', ['create_datetime'], unique=False)
    op.create_index(op.f('ix_question_movie_id'), 'question', ['movie_id'], unique=False)
    op.create_index(op.f('ix_question_points'), 'question', ['points'], unique=False)
    op.create_index(op.f('ix_question_user_id'), 'question', ['user_id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_create_datetime'), 'answer', ['create_datetime'], unique=False)
    op.create_index(op.f('ix_answer_movie_id'), 'answer', ['movie_id'], unique=False)
    op.create_index(op.f('ix_answer_points'), 'answer', ['points'], unique=False)
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_user_id'), 'answer', ['user_id'], unique=False)
    op.create_table('question_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_votes_question_id'), 'question_votes', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_votes_user_id'), 'question_votes', ['user_id'], unique=False)
    op.create_table('answer_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_votes_answer_id'), 'answer_votes', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_votes_user_id'), 'answer_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_votes_user_id'), table_name='answer_votes')
    op.drop_index(op.f('ix_answer_votes_answer_id'), table_name='answer_votes')
    op.drop_table('answer_votes')
    op.drop_index(op.f('ix_question_votes_user_id'), table_name='question_votes')
    op.drop_index(op.f('ix_question_votes_question_id'), table_name='question_votes')
    op.drop_table('question_votes')
    op.drop_index(op.f('ix_answer_user_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_points'), table_name='answer')
    op.drop_index(op.f('ix_answer_movie_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_create_datetime'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_user_id'), table_name='question')
    op.drop_index(op.f('ix_question_points'), table_name='question')
    op.drop_index(op.f('ix_question_movie_id'), table_name='question')
    op.drop_index(op.f('ix_question_create_datetime'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_points'), table_name='user')
    op.drop_index(op.f('ix_user_join_datetime'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_movie_points'), table_name='movie')
    op.drop_index(op.f('ix_movie_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_imdb_id'), table_name='movie')
    op.drop_index(op.f('ix_movie_create_datetime'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
